const express = require('express');
const router = express.Router();
const winston = require('../config/winston');
const { Table, TableRow } = require('../models/tables');
const {
  buildConditionsQuery,
  buildUpdateSet,
} = require('../utils/tablesUtil');
const {
  generateColumnId,
  getColumnStorageKey,
  schemaFromLegacyMap,
  isLegacySchemaMap,
  isColumnDefinitionArray,
  isSchemaMetadataArray,
  getTableSchema,
  findColumnById,
  resolveColumnId,
  resolveDataKeys,
  ensureTableSchemaPersisted,
} = require('../utils/tablesColumnResolver');
const { ensureRowColumnIndex } = require('../utils/tablesIndex');


function deprecationWarn(message) {
  winston.warn(`[tables] ${message}`);
}

function resolveRowPayload(data, schema) {
  return resolveDataKeys(data, schema, deprecationWarn);
}

function normalizeInputSchema(inputSchema, { rejectClientIds = false } = {}) {
  if (!Array.isArray(inputSchema) || inputSchema.length === 0) {
    throw new Error('schema must be a non-empty array');
  }
  return inputSchema.map((col, index) => {
    if (!col || typeof col !== 'object') {
      throw new Error(`Invalid column at index ${index}`);
    }
    if (rejectClientIds && typeof col.id === 'string' && col.id.length > 0) {
      throw new Error(`Column id must not be provided at index ${index}; ids are generated by the server`);
    }
    const name = col.name;
    const type = col.type || 'string';
    if (typeof name !== 'string' || name.length === 0) {
      throw new Error(`Invalid column name at index ${index}`);
    }
    const key = typeof col.key === 'string' && col.key.length > 0 ? col.key : name;
    const id = rejectClientIds || typeof col.id !== 'string' || col.id.length === 0
      ? generateColumnId()
      : col.id;
    return {
      id,
      name,
      key,
      type,
      index: typeof col.index === 'number' ? col.index : index,
      indexed: Boolean(col.indexed),
    };
  });
}

function resolveSchemaInput(schema, options = {}) {
  if (isColumnDefinitionArray(schema)) {
    return normalizeInputSchema(schema, options);
  }
  if (isLegacySchemaMap(schema)) {
    return schemaFromLegacyMap(schema);
  }
  throw new Error('schema must be a column metadata array or a legacy name-to-type map');
}

function buildTablePayload({ name, schema }) {
  if (!schema) {
    throw new Error('schema is required');
  }
  return {
    name,
    schema: resolveSchemaInput(schema, { rejectClientIds: true }),
  };
}

async function loadTableWithSchema(id_project, id_table) {
  let table = await Table.findOne({ id_project, _id: id_table });
  if (!table) {
    return null;
  }
  table = await ensureTableSchemaPersisted(table, Table);
  return table;
}

function tableResponse(table) {
  const obj = table.toObject ? table.toObject() : table;
  obj.schema = getTableSchema(table);
  delete obj.columns;
  return obj;
}

function rowResponse(row) {
  const obj = row.toObject ? row.toObject() : row;
  return { _id: obj._id, ...(obj.data || {}) };
}


// ######## TABLES ENDPOINTS ########

/**
 * Get all tables for a project
 */
router.get('/', async (req, res) => {
  const id_project = req.projectid;

  try {
    const tables = await Table.find({ id_project });
    return res.status(200).send(tables.map(tableResponse));
  } catch (error) {
    winston.error('Error finding tables: ', error);
    return res.status(500).send({ success: false, error: 'Error finding tables' });
  }
});

/**
 * Get a table by id
 */
router.get('/:id', async (req, res) => {
  const id_project = req.projectid;
  const id_table = req.params.id;

  try {
    const table = await loadTableWithSchema(id_project, id_table);
    if (!table) {
      return res.status(404).send({ success: false, error: 'Table not found' });
    }

    const tableRows = await TableRow.find({ id_project, id_table });
    const tableObj = tableResponse(table);
    tableObj.rows = tableRows.map(rowResponse);

    return res.status(200).send(tableObj);
  }
  catch (error) {
    winston.error('Error finding table: ', error);
    return res.status(500).send({ success: false, error: 'Error finding table' });
  }
});

/**
 * Create a new table
 */
router.post('/', async (req, res) => {
  const id_project = req.projectid;
  const { name, schema } = req.body;

  let payload;
  try {
    payload = buildTablePayload({ name, schema });
  } catch (validationError) {
    return res.status(400).send({ success: false, error: validationError.message });
  }

  const table = new Table({
    id_project,
    name,
    schema: payload.schema,
    createdBy: req.user.id,
  });

  try {
    const savedTable = await table.save();
    const schemaCols = getTableSchema(savedTable);
    for (const col of schemaCols) {
      if (col.indexed) {
        await ensureRowColumnIndex(TableRow.collection, id_project, savedTable._id.toString(), getColumnStorageKey(col));
      }
    }
    return res.status(200).send(tableResponse(savedTable));
  }
  catch (error) {
    winston.error('Error creating table: ', error);
    return res.status(500).send({ success: false, error: 'Error creating table' });
  }
});

/**
 * Update a table
 */
router.put('/:id', async (req, res) => {
  const id_project = req.projectid;
  const id_table = req.params.id;
  const { name, schema } = req.body;

  const update = {};
  if (name !== undefined) {
    update.name = name;
  }
  if (schema !== undefined) {
    try {
      update.schema = resolveSchemaInput(schema);
    } catch (validationError) {
      return res.status(400).send({ success: false, error: validationError.message });
    }
  }

  try {
    const table = await Table.findOneAndUpdate(
      { id_project, _id: id_table },
      { ...update, $unset: { columns: 1 } },
      { new: true }
    );
    if (!table) {
      return res.status(404).send({ success: false, error: 'Table not found with id: ' + id_table });
    }
    return res.status(200).send(tableResponse(table));
  }
  catch (error) {
    winston.error('Error updating table: ', error);
    return res.status(500).send({ success: false, error: 'Error updating table' });
  }
});

/**
 * Rename column metadata only (no row updates).
 * PATCH /:id/columns/:columnId  body: { name }
 */
router.patch('/:id/columns/:columnId', async (req, res) => {
  const id_project = req.projectid;
  const id_table = req.params.id;
  const columnId = req.params.columnId;
  const { name: newName } = req.body;

  if (typeof newName !== 'string' || newName.trim().length === 0) {
    return res.status(400).send({ success: false, error: 'name is required' });
  }
  const trimmedName = newName.trim();

  try {
    const table = await loadTableWithSchema(id_project, id_table);
    if (!table) {
      return res.status(404).send({ success: false, error: 'Table not found' });
    }

    const schema = getTableSchema(table);
    const col = findColumnById(schema, columnId);
    if (!col) {
      return res.status(404).send({ success: false, error: 'Column not found' });
    }

    if (col.name === trimmedName) {
      return res.status(200).send(tableResponse(table));
    }

    const duplicate = schema.some(c => c.id !== columnId && c.name === trimmedName);
    if (duplicate) {
      return res.status(409).send({ success: false, error: 'Column name already exists' });
    }

    const storageKey = getColumnStorageKey(col);

    const updatedSchema = schema.map(c => {
      if (c.id === columnId) {
        return { ...c, name: trimmedName, key: storageKey };
      }
      return c;
    });

    const updatedTable = await Table.findOneAndUpdate(
      { id_project, _id: id_table },
      { schema: updatedSchema, $unset: { columns: 1 } },
      { new: true }
    );

    return res.status(200).send(tableResponse(updatedTable));
  } catch (error) {
    winston.error('Error renaming column: ', error);
    return res.status(500).send({ success: false, error: 'Error renaming column' });
  }
});

/**
 * Delete a table
 */
router.delete('/:id/delete', async (req, res) => {
  const id_project = req.projectid;
  const id_table = req.params.id;

  try {
    const table = await Table.findOneAndDelete({ id_project, _id: id_table });
    if (!table) {
      return res.status(404).send({ success: false, error: 'Table not found' });
    }
    await TableRow.deleteMany({ id_project, id_table });
    return res.status(200).send({ success: true, message: 'Table deleted successfully' });
  }
  catch (error) {
    winston.error('Error deleting table: ', error);
    return res.status(500).send({ success: false, error: 'Error deleting table' });
  }
});


// ######## ROWS ENDPOINTS ########

/**
 * Get all rows for a table
 */
router.get('/:id/rows', async (req, res) => {
  const id_project = req.projectid;
  const id_table = req.params.id;

  try {
    const rows = await TableRow.find({ id_project, id_table });
    const rowObj = rows.map(rowResponse);
    return res.status(200).send(rowObj);
  }
  catch (error) {
    winston.error('Error finding rows: ', error);
    return res.status(500).send({ success: false, error: 'Error finding rows' });
  }
});

/**
 * Get a row by id
 */
router.get('/:id/row', async (req, res) => {
    return res.status(200).send({ success: true, message: 'Row not found' });
})
  
/**
 * Insert a new row into a table
 */
router.put('/:id/insert', async (req, res) => {
  const id_project = req.projectid;
  const id_table = req.params.id;
  const { data } = req.body;

  try {
    const table = await loadTableWithSchema(id_project, id_table);
    if (!table) {
      return res.status(404).send({ success: false, error: 'Table not found' });
    }

    const schema = getTableSchema(table);
    let rowData;
    try {
      rowData = resolveRowPayload(data, schema);
    } catch (validationError) {
      return res.status(400).send({ success: false, error: validationError.message });
    }

    const tableRow = await TableRow.create({ id_project, id_table, data: rowData });
    return res.status(200).send(tableRow);
  }
  catch (error) {
    winston.error('Error inserting row: ', error);
    return res.status(500).send({ success: false, error: 'Error inserting row' });
  }
});

/**
 * Update a row in a table
 */
router.put('/:id/update', async (req, res) => {
  const id_project = req.projectid;
  const id_table = req.params.id;
  const { id_row, must_match, conditions } = req.body;
  const data = req.body.data;

  try {
    const table = await loadTableWithSchema(id_project, id_table);
    if (!table) {
      return res.status(404).send({ success: false, error: 'Table not found' });
    }

    const schema = getTableSchema(table);
    let update;

    try {
      update = buildUpdateSet(data, schema, deprecationWarn);
    } catch (validationError) {
      return res.status(400).send({ success: false, error: validationError.message });
    }

    if (id_row) {
      const row = await TableRow.findOneAndUpdate(
        { id_project, id_table, _id: id_row },
        update,
        { new: true }
      );
      if (!row) {
        return res.status(404).send({ success: false, error: 'Row not found' });
      }
      return res.status(200).send(row);
    }

    if (!conditions) {
      return res.status(400).send({ success: false, error: 'id_row or conditions is required' });
    }

    let conditionsQuery;
    try {
      conditionsQuery = buildConditionsQuery(conditions, must_match, schema, deprecationWarn);
    } catch (validationError) {
      return res.status(400).send({ success: false, error: validationError.message });
    }

    const filter = { id_project, id_table, ...conditionsQuery };
    const row = await TableRow.findOneAndUpdate(filter, update, { new: true });
    if (!row) {
      return res.status(404).send({ success: false, error: 'Row not found' });
    }
    return res.status(200).send(row);
  } catch (error) {
    winston.error('Error updating row: ', error);
    return res.status(500).send({ success: false, error: 'Error updating row' });
  }
});

/**
 * Upsert a row in a table
 */
router.put('/:id/upsert', async (req, res) => {
  const id_project = req.projectid;
  const id_table = req.params.id;
  const { id_row, must_match, conditions, multi } = req.body;
  const data = req.body.data;

  try {
    const table = await loadTableWithSchema(id_project, id_table);
    if (!table) {
      return res.status(404).send({ success: false, error: 'Table not found' });
    }

    const schema = getTableSchema(table);
    let update;
    let rowData;

    try {
      update = buildUpdateSet(data, schema, deprecationWarn);
      rowData = resolveRowPayload(data, schema);
    } catch (validationError) {
      return res.status(400).send({ success: false, error: validationError.message });
    }

    if (id_row) {
      const filter = { id_project, id_table, _id: id_row };
      const existing = await TableRow.findOne(filter);

      if (existing) {
        const row = await TableRow.findOneAndUpdate(filter, update, { new: true });
        return res.status(200).send(row);
      }

      try {
        const row = await TableRow.create({ _id: id_row, id_project, id_table, data: rowData });
        return res.status(200).send(row);
      } catch (createError) {
        if (createError.code === 11000) {
          const row = await TableRow.findOneAndUpdate(filter, update, { new: true });
          if (row) {
            return res.status(200).send(row);
          }
        }
        throw createError;
      }
    }

    if (!conditions) {
      return res.status(400).send({ success: false, error: 'id_row or conditions is required' });
    }

    let conditionsQuery;
    try {
      conditionsQuery = buildConditionsQuery(conditions, must_match, schema, deprecationWarn);
    } catch (validationError) {
      return res.status(400).send({ success: false, error: validationError.message });
    }

    const filter = { id_project, id_table, ...conditionsQuery };
    const matches = await TableRow.find(filter);

    if (multi === true) {
      if (matches.length === 0) {
        const row = await TableRow.create({ id_project, id_table, data: rowData });
        return res.status(200).send([row]);
      }

      await TableRow.updateMany(filter, update);
      const rows = await TableRow.find(filter);
      return res.status(200).send(rows);
    }

    if (matches.length > 1) {
      return res.status(409).send({ success: false, error: 'Multiple rows match the conditions' });
    }

    if (matches.length === 1) {
      const row = await TableRow.findOneAndUpdate(filter, update, { new: true });
      return res.status(200).send(row);
    }

    const row = await TableRow.create({ id_project, id_table, data: rowData });
    return res.status(200).send(row);
  } catch (error) {
    winston.error('Error upserting row: ', error);
    return res.status(500).send({ success: false, error: 'Error upserting row' });
  }
});

/**
 * Delete a row from a table
 */
router.put('/:id/delete', async (req, res) => {
  const id_project = req.projectid;
  const id_table = req.params.id;
  const { data } = req.body;

  try {
    const table = await TableRow.findOneAndDelete({ id_project, id_table, data });
    return res.status(200).send(table);
  }
  catch (error) {
    winston.error('Error deleting row: ', error);
    return res.status(500).send({ success: false, error: 'Error deleting row' });
  }
});

module.exports = router;
module.exports.resolveColumnIdForTable = async (id_project, id_table, columnId) => {
  const table = await loadTableWithSchema(id_project, id_table);
  if (!table) {
    throw new Error('Table not found');
  }
  return resolveColumnId(getTableSchema(table), columnId);
};
