"use strict";

/**
 * Central permission identifiers for RBAC and route guards.
 * Used by permission.middleware.requirePermission against the per-role sets in config/roles.js.
 */

module.exports = {
  REQUEST_READ_ALL: "request_read_all",
  REQUEST_READ_GROUP: "request_read_group",
  REQUEST_READ_MINE: "request_read_my",
  INBOX_READ: "inbox_read",
  REQUEST_UNASSIGNED_NOTIFICATION_READ: "request_unassigned_notification_read",
  REQUEST_SEND: "request_send",
  REQUEST_CLOSE: "request_close",
  REQUEST_JOIN: "request_join",
  REQUEST_REOPEN: "request_reopen",
  REQUEST_DELETE: "request_delete",
  REQUEST_UPDATE_STATUS: "request_update_status",
  REQUEST_UPDATE_PRIORITY: "request_update_priority",
  REQUEST_UPDATE_FOLLOWERS: "request_update_followers",
  REQUEST_UPDATE_SMART_ASSIGNMENT: "request_update_smart_assignment",
  REQUEST_UPDATE_TAGS: "request_update_tags",
  REQUEST_UPDATE_NOTES: "request_update_notes",
  REQUEST_REASSIGN: "request_reassign",
  REQUEST_ADD: "request_add",
  REQUEST_LEFT: "request_left",
  REQUEST_TRANSCRIPT_SEND: "request_transcript_send",
  HISTORY_READ: "history_read",
  HISTORY_FILTER_BY_AGENT: "history_filter_by_agent",
  REQUESTS_EXPORT: "requests_export",
  CONVERSATION_DETAIL_READ: "conversation_detail_read",
  TICKET_ID_READ: "ticket_id_read",
  RATING_READ: "rating_read",
  TAGS_READ_ALL: "tags_read_all",
  CHANGE_PROJECT: "change_project",
  SIMULATE_CONV: "simulate_conv",
  QUOTA_USAGE_READ: "quota_usage_read",
  AUTOMATIONSLOG_READ: "automationslog_read",
  AUTOMATIONSLOG_CREATE: "automationslog_create",
  KB_PROXY_QA: "kb_proxy_qa",
  KB_PROXY_INDEX: "kb_proxy_index",
  KB_NAMESPACE_LIST: "kb_namespace_list",
  KB_NAMESPACE_CREATE: "kb_namespace_add", //kb_namespace_create
  KB_NAMESPACE_IMPORT: "kb_namespace_import",
  KB_NAMESPACE_EXPORT: "kb_namespace_export",
  KB_NAMESPACE_DELETE: "kb_namespace_delete",
  KB_READ: "kb_read",
  KB_CONTENT_ADD: "kb_contents_add",
  KB_CONTENT_UPDATE: "kb_content_update",
  KB_CONTENT_DELETE: "kb_content_delete",
  KB_CONTENT_REINDEX: "kb_content_reindex",
  KB_CONTENT_CHECK_STATUS: "kb_content_check_status",
  KB_SETTINGS_EDIT: "kb_settings_edit",
  KB_DELETE: "kb_delete",
  KB_CONTENTS_EXPORT: "kb_contents_export",
  LLM_PREVIEW: "llm_preview",
  LLM_TRANSCRIPTION: "llm_transcription",
  FLOWS_LIST: "flows_read", // flows_list
  FLOW_READ: "flow_read",
  FLOW_READ_PUBLISHED: "flow_read_published",
  FLOW_CREATE: "flow_add", // flow_create
  FLOW_UPDATE: "flow_edit", // flow_update
  FLOW_TEST: "flow_test",
  FLOW_PUBLISH: "flow_publish", 
  FLOW_DUPLICATE: "flow_duplicate", // flow_duplicate
  FLOW_DELETE: "flow_delete", // flow_delete
  FLOW_SHARE: "flow_share", // flow_share
  FLOW_EXPORT: "flow_export", // flow_export
  FLOW_WEBHOOK_COPY: "flow_webhook_copy", // flow_webhook_copy
  FLOW_WEBHOOK_EDIT: "flow_webhook_edit", // flow_webhook_edit
  FLOW_WEBHOOK_DELETE: "flow_webhook_delete", // flow_webhook_delete
  LEAD_CREATE: "lead_create",
  LEAD_LIST: "leads_list",
  LEAD_READ: "leads_read",
  LEAD_UPDATE: "lead_update",
  LEAD_RESTORE: "lead_restore",
  LEAD_TRASH: "lead_trash",
  LEAD_DELETE: "lead_delete",
  LEADS_EXPORT: "leads_export",
  LEAD_BAN: "lead_ban",
  LEAD_UNBAN: "lead_unban",
  ANALYTICS_READ: "analytics_read",
  ACTIVITIES_READ: "activities_read",
  WIDGETSETUP_READ: "widgetsetup_read",
  DEPARTMENT_LIST: "department_list",
  DEPARTMENT_READ: "department_read",
  DEPARTMENT_CREATE: "department_create",
  DEPARTMENT_UPDATE: "department_update",
  DEPARTMENT_DELETE: "department_delete",
  DEPARTMENT_LIST_READ: "department_list_read",// ###
  DEPARTMENT_DETAIL_READ: "department_detail_read",// ###
  DEPARTMENT_CREATE_READ: "department_create_read",// ###
  TEAMMATES_READ: "teammates_read",
  TEAMMATE_UPDATE: "teammate_update",
  TEAMMATES_CREATE: "teammates_create",
  ROLES_READ: "roles_read",
  ROLES_CREATE: "roles_create",
  ROLES_UPDATE: "roles_update",
  ROLE_DELETE: "role_delete",
  GROUPS_READ: "groups_read",
  GROUPS_CREATE: "groups_create",
  GROUP_UPDATE: "group_update",
  GROUP_DELETE: "group_delete",
  EMAIL_TICKETING_READ: "email_ticketing_read",
  EMAIL_TICKETING_UPDATE: "email_ticketing_update",
  CANNED_RESPONSES_READ: "canned_responses_read",
  CANNED_RESPONSES_UPDATE: "canned_responses_update",
  CANNED_RESPONSES_CREATE: "canned_responses_create",
  CANNED_RESPONSES_DELETE: "canned_responses_delete",
  TAGS_READ: "tags_read",
  TAG_CREATE: "tag_create",
  TAG_DELETE: "tag_delete",
  TAG_UPDATE: "tag_update",
  HOURS_READ: "hours_read",
  HOURS_UPDATE: "hours_update",
  HOURS_DELETE: "hours_delete",
  HOURS_CREATE: "hours_create",
  INTEGRATIONS_LIST: "integrations_read", // integrations_list
  INTEGRATION_CREATE: "integration_create",
  INTEGRATION_READ: "integration_read",
  INTEGRATION_UPDATE: "integrations_update",
  INTEGRATION_DELETE: "integration_delete",
  APPS_READ: "apps_read",
  APPS_UPDATE: "apps_update",
  PROJECTSETTINGS_GENERAL_READ: "projectsettings_general_read",
  PROJECTSETTINGS_GENERAL_UPDATE: "projectsettings_general_update",
  PROJECTSETTINGS_DEVELOPER_READ: "projectsettings_developer_read",
  PROJECTSETTINGS_DEVELOPER_UPDATE: "projectsettings_developer_update",
  PROJECTSETTINGS_SMARTASSIGNMENT_READ: "projectsettings_smartassignment_read",
  PROJECTSETTINGS_SMARTASSIGNMENT_UPDATE: "projectsettings_smartassignment_update",
  PROJECTSETTINGS_NOTIFICATION_READ: "projectsettings_notification_read",
  PROJECTSETTINGS_SECURITY_READ: "projectsettings_security_read",
  PROJECTSETTINGS_BANNED_READ: "projectsettings_banned_read",
  PROJECTSETTINGS_ADVANCED_READ: "projectsettings_advanced_read",
  PU_INVITE: "pu_invite",
  PU_CREATE: "pu_create",
  PU_UPDATE: "pu_update",
  PU_UPDATE_MINE: "pu_update_mine",
  PU_DELETE: "pu_delete",
  PU_RESTORE: "pu_restore",
  PU_READ: "pu_read",
  APIKEY_READ: "apikey_read",
  APIKEY_CREATE: "apikey_create",
  APIKEY_UPDATE: "apikey_update",
  APIKEY_DELETE: "apikey_delete",

}
