name: Docker Enterprise Latest Image CI

on:	
  push:	 
    branches: [ master ]
  pull_request:	
    branches: [ master ]	

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2	     
      name: Check out the repo
    - uses: docker/build-push-action@v1
      with:	    
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        build_args: NPM_TOKEN=${{ secrets.NPM_TOKEN }}
        dockerfile: Dockerfile-en
        repository: tiledeskrepo/tiledesk-server-enterprise
        tags: latest
