name: Docker Image Community latest CI

on:	
  push:	 
    branches: [ master ]
  pull_request:	
    branches: [ master ]	

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2	     
      name: Check out the repo
    - uses: docker/build-push-action@v1
      with:	    
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: tiledesk/tiledesk-server
        tags: latest
